### PR TITLE
Wacom i2c support

### PR DESCRIPTION
**Pull request by flying-elephant**
This is updated version of the last review of the commits "b7eee98efb159a548555fc698970cba177e97e52" and
"3601278bf924be797ef79db584f25ffa88c4ea37".

### CODE REVIEW

**Comment by flying-elephant** [comment]
Please review these files again.
Thanks you.

**Comment by jigpu** [comment]
Would you mind splitting the second commit into two? The first would be a "clean" copy of the wacom_i2c driver from commit fafc66387dc0. The second commit would then add the new modifications. This will make it obvious what changes we're making compared to upstream and why.

The only other thing's I'd note are a minor spelling error in the 2nd commit description ("convers" -> "covers") and to wrap it to 80 characters when possible (obviously the URL can't be wrapped, but the others can). I think we can / should ignore all the other warnings produced by the Github checks.

**Comment by flying-elephant** [comment]
> Would you mind splitting the second commit into two? The first would be a "clean" copy of the wacom_i2c driver from commit fafc66387dc0. The second commit would then add the new modifications. This will make it obvious what changes we're making compared to upstream and why.
> 
> The only other thing's I'd note are a minor spelling error in the 2nd commit description ("convers" -> "covers") and to wrap it to 80 characters when possible (obviously the URL can't be wrapped, but the others can). I think we can / should ignore all the other warnings produced by the Github checks.

Sure, I understand it.
However, while I was bringing the original wacom_i2c.c from the commit, I realized that my wacom_i2c had an old format comparing to the latest one.
I need to modify my wacom_i2c and test it again.
Please buy me time.

**Comment by Pinglinux** [comment]
Thank you @flying-elephant for merging the original wacom_i2c.c here. There are two failed checks. The first one looks fine. But the second one : .github/workflows/main.yml / compile (4.5) (pull_request) Failing after 28s — compile (4.5) 
needs to be fixed. You accidentally changed/removed some lines in the 4.5/Makefile.in. Please fix that and push the updated 4.5/Makefile.in again.

**Comment by Pinglinux** [comment]
@flying-elephant Signed-off-by was missing.

The header file missing error requires a ifdef in wacom_i2c.c. For kernels older than 4.19, linux/bitops.h is the header to use [1]. It takes a few rounds to get used to the process, doesn't it ;)? 

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/include/linux/bits.h?h=v4.9.312&id=b995196b9da4e2486d50e132539c848a60ea88da

**Comment by flying-elephant** [comment]
Hi Ping,

Thank you for checking.
So, eventually wacom_i2c from linux.org requires a bit custom for getting compiled correctly for 4.5 of yours?

Tats

**Comment by Pinglinux** [comment]
> wacom_i2c from kernel.org requires a bit custom for getting compiled correctly for 4.5 of yours?

You are right. Even wacom.ko added #if-statement to be compiled for all kernels 4.5 or later. You can search "#if" in wacom_wac.c and wacom_sys.c to get some ideas. For wacom_wac.c, https://github.com/linuxwacom/input-wacom/blob/master/4.5/wacom_wac.c#L1855 gives you one example. https://github.com/linuxwacom/input-wacom/blob/master/4.5/wacom_sys.c#L22 gives you an example in wacom_sys.c.

The #if-statement is to make the same codebase work under different kernel versions since some header files/interfaces have been changed while kernel updated from 4.5 to the latest version. Since there were no major Input layer changes in the kernels between 4.5 to now, we kept the same codebase to save some maintenance effort.

You need to check if the kernel is 4.19 or later to include the correct header file for the code to compile, as I mentioned in my last comment.

**Comment by flying-elephant** [comment]
Hi Ping,

I modified wacom_i2c.c in order to support kernel version later than and on 4.5.
Please review. thank you for taking your time again!

Tats

**Comment by Pinglinux** [comment]
@flying-elephant there were still two errors in you last PR: missing signed-off and data type error. I merged it anyway. I'll correct the data type error so the code can be compiled. Please remember to put "Signed-of-by" in your future patches.

Thank you for your effort,
Ping

**Comment by Pinglinux** [comment]
I almost wanted to revert the commit since the commit history is not clean. We'd like to have a commit history that reflects a meaningful evolution of the development that helps future "us" to easily follow the technical changes of a code base. Correcting development errors and testing should happen either offline or in our own branch under our own repository. This is Tats' first contribution and wacom_i2c.c will probably not have too many changes. Let it be...

**Pull request merged**
