### PR TITLE
5.3 backports

### PR DESCRIPTION
**Pull request by skomra**
Pull the latest patches accepted upstream and backport them.

Signed-off-by: Aaron Armstrong Skomra <aaron.skomra@wacom.com>

### CODE REVIEW

**Comment by jigpu** [comment]
Looks good, though a few notes:
* Commit 2874c5fd28 from upstream also needs to be brought over
* It looks like part of the "HID: wacom: Add 2nd gen Intuos Pro Small support" patch was accidentally removed in the middle of upstream merge commit 74acee309f. We'll need to send out a patch adding it back in...
* All the CI failures are just checkpatch being angry at patches that had previously been accepted
  * There are "WARNING: Duplicate signature" messages that I'll have to take care of to prevent future backports from also failing Travis

**Comment by skomra** [comment]
I brought over that commit for the 4.5 and 3.17 paths. I will make a fix for the merge commit issue and submit that later as a separate PR.

**Comment by jigpu** [comment]
Any particular reason to not backport the SPDX patch to the 2.6.x trees too?

**Comment by skomra** [comment]
I didn't see any particular reason to backport them, but I don't object. I'll add them.

**Comment by skomra** [comment]
For the record that upstream commit left some empty comment blocks and an inconsistency (both C++ and C style comments). I guess we could address that later upstream if we want.

**Review by jigpu — APPROVED** [review]
Reviewed-by: Jason Gerecke <jason.gerecke@wacom.com>

**Comment by skomra** [comment]
To follow up on my merge commit comment above, I couldn't submit that merge commit fix as a PR here because that missing line is already in our repo. For reference here is that patch:

https://patchwork.kernel.org/patch/11090665/

**Pull request merged**
