### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by jigpu**
Address a few compiler warnings that I've bumped into.

### CODE REVIEW

**Comment by skomra** [comment]
I was about to add my reviewed by and then I remembered the patch checklist which asked me to check for the magic numbers. I guess 42 is the most magic of the magic numbers. Maybe it gets a pass...

With that said:
Reviewed-by: Aaron Armstrong Skomra <aaron.skomra@wacom.com>

**Comment by jigpu** [comment]
Ah, good catch. I'll add a define and send it up to the list.

**Comment by jigpu** [comment]
Patches sent and waiting on upstream.

**Comment by jigpu** [comment]
HID patches cherry-picked to for-5.4 and master. Still waiting on input patches.

**Comment by jigpu** [comment]
Input patches cherry-picked to for-5.4 and master.

**Pull request closed without merging**
