### PR TITLE
Fix issue 98

### PR DESCRIPTION
**Pull request by jigpu**

### CODE REVIEW

**Comment by skomra** [comment]
Jason did this make it upstream yet? I didn't see it at kernel/git/hid/hid.git.

**Comment by jigpu** [comment]
Nope, I was just pushing this here first for pre-review but chose the wrong merge branch, just like with #108.

**Comment by skomra** [comment]
I think you already sent this [v2] to LInux-input:

https://patchwork.kernel.org/patch/11082737/

**Comment by jigpu** [comment]
Indeed, and it looks like it was just pulled into upstream.

As a matter of procedure, how do we want to handle the next step? Just edit the commit(s) with the now-available "imported" lines and then merge?

**Comment by jigpu** [comment]
Commits merged by cherry-picking onto our "for-5.3" and "master" branches.

**Pull request closed without merging**
