### PR TITLE
Update automated release workflow

### PR DESCRIPTION
**Pull request by Joshua-Dickens**
Cleaned up checksum generation, got rid of old soon to be deprecated set_output styling for the new styling recommended by github, and small formatting changes that should make the autogenerated release text cleaner.

### CODE REVIEW

**Review by whot — APPROVED** [review]
@Joshua-Dickens can you fix your editor please so git commit messages don't exceed 78 characters? I think that's a requirement for most projects anyway (and it improves readability).

other than that, this LGTM, thanks!

**Comment by whot** [comment]
the checkpatch job should be taught to ignore commits that don't touch the kernel directories...

**Comment by Joshua-Dickens** [comment]
@whot 
Fixed my editor, don't know why I haven't done it before since it'll help with me forgetting commit formatting. As for the checkpatch that's something we can look into, I took a quick peek at the config options for the action we're using and I don't see anything in there that might help with that so we'll have to add some logic to the workflow itself. Something I can look into knocking out.

**Comment by whot** [comment]
quick google found [this link](https://how.wtf/run-workflow-step-or-job-based-on-file-changes-github-actions.html) - since we have checkpatch as a separate workflow already it seems like it's just a matter of adding `paths` to the top-level `on`

**Comment by Joshua-Dickens** [comment]
Yeah that seems like it would do the trick.
Went ahead and rewrote the commit message to make it a bit cleaner and with that this merge should be good.

**Pull request merged**
